In [2]:
#Reading in the census dataset
import pandas as pd
import numpy as np
census = pd.read_csv("census.csv")#reading in the census dataset
census.head(10)

census_year state_fips_code  total_family_income  age     sex  \
0         2000         Florida              14550.0   44    Male   
1         2000         Florida              22800.0   20  Female   
2         2000         Florida                  0.0   20    Male   
3         2000         Florida              23000.0    6  Female   
4         2000         Florida              48000.0   55    Male   
5         2000         Florida              74000.0   43  Female   
6         2000         Florida              23000.0   60  Female   
7         2000         Florida              74000.0   47  Female   
8         2000         Florida              60000.0   54  Female   
9         2000         Florida              14600.0   58  Female   

      race_general          marital_status  total_personal_income  
0  Two major races  Married/spouse present                    0.0  
1            White    Never married/single                13000.0  
2            Black    Never married/single                20000.0  
3            White    Never married/single                    NaN  
4            White  Married/spouse present                36000.0  
5            White  Married/spouse present                27000.0  
6            White  Married/spouse present                11800.0  
7            White  Married/spouse present                48000.0  
8            Black  Married/spouse present                40000.0  
9            White                 Widowed                14600.0

In [2]:
census.head(10)

census_year state_fips_code  total_family_income  age     sex  \
0         2000         Florida              14550.0   44    Male   
1         2000         Florida              22800.0   20  Female   
2         2000         Florida                  0.0   20    Male   
3         2000         Florida              23000.0    6  Female   
4         2000         Florida              48000.0   55    Male   
5         2000         Florida              74000.0   43  Female   
6         2000         Florida              23000.0   60  Female   
7         2000         Florida              74000.0   47  Female   
8         2000         Florida              60000.0   54  Female   
9         2000         Florida              14600.0   58  Female   

      race_general          marital_status  total_personal_income  
0  Two major races  Married/spouse present                    0.0  
1            White    Never married/single                13000.0  
2            Black    Never married/single                20000.0  
3            White    Never married/single                    NaN  
4            White  Married/spouse present                36000.0  
5            White  Married/spouse present                27000.0  
6            White  Married/spouse present                11800.0  
7            White  Married/spouse present                48000.0  
8            Black  Married/spouse present                40000.0  
9            White                 Widowed                14600.0

In [3]:
#dropping the column state_fips_code column
census = census.drop(["state_fips_code"], axis = 1)

In [4]:
census.tail(5)

census_year  total_family_income  age     sex race_general  \
495         2000               8500.0   68  Female        White   
496         2000              55400.0   12    Male        White   
497         2000              15000.0   60    Male        Black   
498         2000                  NaN   60    Male        Black   
499         2000              39370.0   47    Male        White   

             marital_status  total_personal_income  
495                Divorced                 8500.0  
496    Never married/single                    NaN  
497                 Widowed                15000.0  
498   Married/spouse absent                48600.0  
499  Married/spouse present                19800.0

In [5]:
#Identifying the columns in the census dataset
print(census.columns)

Index(['census_year', 'total_family_income', 'age', 'sex', 'race_general',
       'marital_status', 'total_personal_income'],
      dtype='object')


In [6]:
#selecting out integer index labels from 12-34 
census.iloc[12:34]

census_year  total_family_income  age     sex race_general  \
12         2000              32000.0   62  Female        White   
13         2000             113000.0    8    Male        White   
14         2000              76900.0   25    Male        White   
15         2000             100100.0   44  Female        White   
16         2000              48000.0   28  Female        White   
17         2000              48000.0    1    Male        White   
18         2000              57200.0   31    Male        White   
19         2000              43950.0   69  Female        White   
20         2000              49000.0   31    Male        White   
21         2000              31600.0   80  Female        White   
22         2000              50090.0    2    Male        White   
23         2000              64800.0   47    Male        White   
24         2000              90000.0   12    Male        White   
25         2000              38320.0   47    Male        White   
26         2000             103700.0    8  Female        White   
27         2000                  0.0   67    Male        Black   
28         2000              70700.0   17  Female        White   
29         2000              64800.0   69  Female        White   
30         2000              60000.0   55    Male        White   
31         2000             118100.0   18  Female        White   
32         2000              21000.0   66  Female        White   
33         2000              40000.0   58  Female        White   

            marital_status  total_personal_income  
12                Divorced                32000.0  
13    Never married/single                    NaN  
14    Never married/single                 6000.0  
15  Married/spouse present                16100.0  
16  Married/spouse present                12000.0  
17    Never married/single                    NaN  
18  Married/spouse present                20000.0  
19  Married/spouse present                 4800.0  
20  Married/spouse present                28000.0  
21                 Widowed                31600.0  
22    Never married/single                    NaN  
23    Never married/single                49300.0  
24    Never married/single                    NaN  
25  Married/spouse present                34320.0  
26    Never married/single                    NaN  
27                 Widowed                 8400.0  
28    Never married/single                 3700.0  
29                Divorced                 4800.0  
30  Married/spouse present                53000.0  
31    Never married/single                 7500.0  
32  Married/spouse present                 6000.0  
33  Married/spouse present                    0.0

In [7]:
#selecting the first 10 rows of the column race_general
census["race_general"].head(10)

0    Two major races
1              White
2              Black
3              White
4              White
5              White
6              White
7              White
8              Black
9              White
Name: race_general, dtype: object

In [8]:
#selecting out rows with total_family_income greater than 50000
census[census["total_family_income"] > 50000].head(10)

census_year  total_family_income  age     sex race_general  \
5          2000              74000.0   43  Female        White   
7          2000              74000.0   47  Female        White   
8          2000              60000.0   54  Female        Black   
13         2000             113000.0    8    Male        White   
14         2000              76900.0   25    Male        White   
15         2000             100100.0   44  Female        White   
18         2000              57200.0   31    Male        White   
22         2000              50090.0    2    Male        White   
23         2000              64800.0   47    Male        White   
24         2000              90000.0   12    Male        White   

            marital_status  total_personal_income  
5   Married/spouse present                27000.0  
7   Married/spouse present                48000.0  
8   Married/spouse present                40000.0  
13    Never married/single                    NaN  
14    Never married/single                 6000.0  
15  Married/spouse present                16100.0  
18  Married/spouse present                20000.0  
22    Never married/single                    NaN  
23    Never married/single                49300.0  
24    Never married/single                    NaN

In [9]:
#Displaying the dimensions of the census dataset
print(census.shape)

(500, 7)


In [10]:
census = pd.DataFrame(census)
census.head(10)

census_year  total_family_income  age     sex     race_general  \
0         2000              14550.0   44    Male  Two major races   
1         2000              22800.0   20  Female            White   
2         2000                  0.0   20    Male            Black   
3         2000              23000.0    6  Female            White   
4         2000              48000.0   55    Male            White   
5         2000              74000.0   43  Female            White   
6         2000              23000.0   60  Female            White   
7         2000              74000.0   47  Female            White   
8         2000              60000.0   54  Female            Black   
9         2000              14600.0   58  Female            White   

           marital_status  total_personal_income  
0  Married/spouse present                    0.0  
1    Never married/single                13000.0  
2    Never married/single                20000.0  
3    Never married/single                    NaN  
4  Married/spouse present                36000.0  
5  Married/spouse present                27000.0  
6  Married/spouse present                11800.0  
7  Married/spouse present                48000.0  
8  Married/spouse present                40000.0  
9                 Widowed                14600.0

In [11]:
#dropping all na values in census dataset
census.dropna()

census_year  total_family_income  age     sex     race_general  \
0           2000              14550.0   44    Male  Two major races   
1           2000              22800.0   20  Female            White   
2           2000                  0.0   20    Male            Black   
4           2000              48000.0   55    Male            White   
5           2000              74000.0   43  Female            White   
..           ...                  ...  ...     ...              ...   
492         2000             119800.0   24    Male            White   
493         2000              18000.0   36    Male            White   
495         2000               8500.0   68  Female            White   
497         2000              15000.0   60    Male            Black   
499         2000              39370.0   47    Male            White   

             marital_status  total_personal_income  
0    Married/spouse present                    0.0  
1      Never married/single                13000.0  
2      Never married/single                20000.0  
4    Married/spouse present                36000.0  
5    Married/spouse present                27000.0  
..                      ...                    ...  
492    Never married/single                22000.0  
493  Married/spouse present                18000.0  
495                Divorced                 8500.0  
497                 Widowed                15000.0  
499  Married/spouse present                19800.0  

[377 rows x 7 columns]

In [12]:
#pivoting a dataset
x = {'Year': [2019, 2019, 2020, 2020], 'Quarter': ['Q1', 'Q2', 'Q1', 'Q2'], 'Sales': [100, 200, 300, 400]}
y = pd.DataFrame(x)
y
y_new = y.pivot(index='Year', columns='Quarter', values='Sales')
y_new


Quarter   Q1   Q2
Year             
2019     100  200
2020     300  400

In [15]:
#Dropping the column census_year in the census dataset
census.head(10)
census_new = census.drop(['census_year'], axis = 1)
census.head(10)


census_year  total_family_income  age     sex     race_general  \
0         2000              14550.0   44    Male  Two major races   
1         2000              22800.0   20  Female            White   
2         2000                  0.0   20    Male            Black   
3         2000              23000.0    6  Female            White   
4         2000              48000.0   55    Male            White   
5         2000              74000.0   43  Female            White   
6         2000              23000.0   60  Female            White   
7         2000              74000.0   47  Female            White   
8         2000              60000.0   54  Female            Black   
9         2000              14600.0   58  Female            White   

           marital_status  total_personal_income  
0  Married/spouse present                    0.0  
1    Never married/single                13000.0  
2    Never married/single                20000.0  
3    Never married/single                    NaN  
4  Married/spouse present                36000.0  
5  Married/spouse present                27000.0  
6  Married/spouse present                11800.0  
7  Married/spouse present                48000.0  
8  Married/spouse present                40000.0  
9                 Widowed                14600.0

In [6]:
census = np.loadtxt('census.csv', delimiter=',',skiprows=(1,2))



TypeError: argument must be an integer

In [12]:
import numpy as np

# load the CSV file into a NumPy array
data = np.genfromtxt('census.csv', delimiter=',')

# extract the column you want to convert to an array
column = data[3:, 7] # replace 2 with the index of the column you want to extract

# convert the column to a NumPy array
column_array = np.array(column)

print(column_array)


[ 2.0000e+04         nan  3.6000e+04  2.7000e+04  1.1800e+04  4.8000e+04
  4.0000e+04  1.4600e+04  2.3000e+04  3.7000e+04  3.2000e+04         nan
  6.0000e+03  1.6100e+04  1.2000e+04         nan  2.0000e+04  4.8000e+03
  2.8000e+04  3.1600e+04         nan  4.9300e+04         nan  3.4320e+04
         nan  8.4000e+03  3.7000e+03  4.8000e+03  5.3000e+04  7.5000e+03
  6.0000e+03  0.0000e+00  4.8000e+03  3.5000e+04  2.0000e+03         nan
  2.4250e+04  8.8000e+03  1.7000e+04  1.2300e+05  1.5570e+04  1.5830e+04
         nan         nan  6.4000e+04  1.7500e+04  0.0000e+00         nan
  4.0000e+03         nan  2.0000e+03  1.0000e+04         nan  3.7100e+04
  1.8000e+03  2.5000e+04  1.2160e+05         nan  5.5300e+04  2.0000e+03
  0.0000e+00         nan  0.0000e+00         nan  1.0500e+05  0.0000e+00
  0.0000e+00  0.0000e+00  1.9900e+04         nan  2.2000e+04  7.2000e+02
  5.5000e+04  3.8000e+04  1.7300e+04         nan  1.4200e+04  1.4500e+04
         nan         nan  4.4004e+04  4.3000e+04   

In [2]:
import pandas as pd
import numpy as np

#Reading in the excel file as a pandas dataframe
df = pd.read_excel('C:/Users/msaim/Downloads/BOLA_RESULTS/Experience Restaurant Survey.xlsm') 

#Converting dataframe to numpy array
data = np.array(df)
data

array([[ 1.,  1., nan],
       [ 5.,  5., nan],
       [ 2.,  2., nan],
       ...,
       [ 4.,  4., nan],
       [ 3.,  3., nan],
       [ 1.,  1., nan]])

In [18]:
data.reshape

<function ndarray.reshape>

In [4]:
#Getting mean

mean = np.mean(data)
mean

nan

In [5]:
#calculating median
median = np.median(data)
median

nan

In [6]:
#Replacing nan with a value
arr_filled = np.nan_to_num(data, nan=0)

print(arr_filled)

[[1. 1. 0.]
 [5. 5. 0.]
 [2. 2. 0.]
 ...
 [4. 4. 0.]
 [3. 3. 0.]
 [1. 1. 0.]]


In [7]:
#Calculating mean again

mean = np.mean(arr_filled)
mean

1.8126666666666666

In [9]:
#Another way of getting mean
my_mean = np.array(arr_filled)
mean = my_mean.mean()
mean

1.8126666666666666

In [8]:
#Calculating median

median = np.median(arr_filled)
median

1.0

In [11]:
#Getting standard deviation
standard_deviation = np.array(arr_filled)
std = standard_deviation.std()
std

#Another way
sta_dev = np.std(arr_filled)
sta_dev

1.7286525259737873

In [17]:
#Broadcasting in numpy
data = np.array(arr_filled)
results = data + 2
print(results)

[[3. 3. 2.]
 [7. 7. 2.]
 [4. 4. 2.]
 ...
 [6. 6. 2.]
 [5. 5. 2.]
 [3. 3. 2.]]


In [18]:
##Broadcasting in another way
results = arr_filled + 1
print(results)

[[2. 2. 1.]
 [6. 6. 1.]
 [3. 3. 1.]
 ...
 [5. 5. 1.]
 [4. 4. 1.]
 [2. 2. 1.]]


In [25]:
## SLICING THE ARRAY TO SELECT ROWS AND COLUMNS

arr = np.array(arr_filled)
sub_array = arr[:5, :1]
sub_array

array([[1.],
       [5.],
       [2.],
       [1.],
       [5.]])

In [28]:
#SLICING CONTINUED

sub_array = arr[ :10, :3]
sub_array

array([[1., 1., 0.],
       [5., 5., 0.],
       [2., 2., 0.],
       [1., 1., 0.],
       [5., 5., 0.],
       [4., 4., 0.],
       [2., 2., 0.],
       [1., 1., 0.],
       [3., 3., 0.],
       [1., 1., 0.]])

In [40]:
##Functions for perfoming element-wise operations on numpy arrays

array_2 = np.array([1,2,0,4])
arr_2 = array_2.reshape(2,2)
print(arr_2)

#Broadcasting new array to division by 3
result = arr_2 % 3
result

#Adding the two arrays
#sum = np.add(arr_2, data)
#print(sum)

[[1 2]
 [0 4]]


array([[1, 2],
       [0, 1]], dtype=int32)

In [43]:
#Using the where function(to select data>12, and replace all data<12 with 5)

new_array = np.where(data > 12, data,5)
print(new_array)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 ...
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [45]:
#Repacing data in array_2
changed_array = np.where(array_2 < 1, array_2, 0)
changed_array


array([0, 0, 0, 0])

In [46]:
#Using the flatten() and ravel() functions
#Creating a flattened array of data

data_flattened = data.flatten()
data_flattened

array([1., 1., 0., ..., 1., 1., 0.])

In [47]:
#Using ravel() to create a new flattened array
data_raveled = data.ravel()
data_raveled

array([1., 1., 0., ..., 1., 1., 0.])

In [51]:
#modifying the array
data[0,0] = 23
print(data_flattened)
print(data_raveled)

[1. 1. 0. ... 1. 1. 0.]
[1. 1. 0. ... 1. 1. 0.]
